data_excel_path: "../data/SPY_Data_Dec2024.xlsx"
all_data_excel_path: "../data/SPY_AllData.xlsx"
atr_multiplier: 0.02
bars_no_to_wait: 9
risk: 0.5
fourier_lookback_window: 100
fourier_n_components: 10
raw_features_g1: "Open,High,Low,Close,BOLLBU,BOLLBM,BOLLBL,DONUP,DONMID,DONLOW,MA20,MA50,MA100,EMA20,PVPTR1,PVPTR2,PVPTR3,PVPT,PVPTS1,PVPTS2,PVPTS3"
raw_features_g2: "ADWM,ADWMMA,WASI,ADJATR,TCHR"
raw_features_g3: "Volume,VOLMA"
raw_features_g4: "Sine_TimeOfDay,Cosine_TimeOfDay"
log_features: "Volume,VOLMA"
shift_and_log_features: "WASI|500"
stand_scale_features: ""
robust_scale_features: "Open,High,Low,Close,BOLLBU,BOLLBM,BOLLBL,DONUP,DONMID,DONLOW,MA20,MA50,MA100,EMA20,PVPTR1,PVPTR2,PVPTR3,PVPT,PVPTS1,PVPTS2,PVPTS3,Sine_TimeOfDay,Cosine_TimeOfDay,ADWM,ADWMMA,WASI,ADJATR,TCHR,Volume,VOLMA"
stand_scaler_path: 'Saved_Data/Regression/stand_scaler.pkl'
robust_scaler_path: 'Saved_Data/Regression/robust_scaler.pkl'
fourier_minmax_path: 'Saved_Data/Regression/fourier_minmax.pkl'
bolband_period: 20
bolband_width: 2
donchn_period: 20
tchr_period: 100
tchr_retracement: "long"
tchr_adj: 5
tchr_range: "highlow"
adwm_period: 14
wasi_limit: 3
volume_ma_period: 10
atr_period: 14
atr_ma: 20
lam: 1.0
alpha: 0.5
use_threshold_optimization: True
num_boosting_rounds: 10000
model_save_name: "Saved_Data/Regression/model1_with_2023_1month_data_reg2.ubj"
label_scales_pickle: "Saved_Data/Regression/label_scales.pkl"
label_power_transform: False
train_start_date: '2023-01-01'
train_end_date: '2023-12-31'
inf_start_date: '2024-01-01'
inf_end_date: '2024-12-30'
label_threshold: 0.8
trade_enter_buy: 0.8
trade_enter_sell: 0.7