data_excel_path: "../data/SPY_Data_Dec2024.xlsx"
all_data_excel_path: "../data/SPY_AllData.xlsx"
atr_multiplier: 0.01
bars_no_to_wait: 24
risk: 0.5
fourier_lookback_window: 100
fourier_n_components: 10
raw_features_g1: "Open,High,Low,Close,BOLLBU,BOLLBM,BOLLBL,DONUP,DONMID,DONLOW,MA20,MA50,MA100,EMA20,PVPTR1,PVPTR2,PVPTR3,PVPT,PVPTS1,PVPTS2,PVPTS3,TCHR"
raw_features_g2: "ADWM,ADWMMA,WASI,ADJATR"
raw_features_g3: "Volume,VOLMA"
raw_features_g4: "Sine_TimeOfDay,Cosine_TimeOfDay"
bolband_period: 20
bolband_width: 2
donchn_period: 20
tchr_period: 100
tchr_retracement: "long"
tchr_adj: 5
tchr_range: "highlow"
adwm_period: 14
wasi_limit: 3
volume_ma_period: 10
atr_period: 14
atr_ma: 20
lam: 1.0
alpha: 0.5
use_threshold_optimization: True
model_save_name: "model1_with_2023_data_auc_recall.ubj"