data_excel_path: "../data/SPY_Data_Dec2024.xlsx"
atr_multiplier: 0.02
bars_no_to_wait: 24
risk: 0.5
fourier_lookback_window: 100
fourier_n_components: 10
raw_features_g1: "Open,High,Low,Close,BOLLBU,BOLLBM,BOLLBL,DONUP,DONMID,DONLOW,MA20,MA50,MA100,EMA20,PVPTR,PVPT,PVPTS,TCHRE"
raw_features_g2: "ADWM,ADWMMA,WASI,ADJATR"
raw_features_g3: "Volume,VOLMA"
