services:


  streamlit:
    build:
      context: .
      dockerfile: ${DOCKER_FILES_DIRECTORY}/Dockerfile_streamlit
      args:
        DAGSTER_TRADING_FUNCTIONS_PATH: ${DAGSTER_TRADING_FUNCTIONS_PATH}
    container_name: streamlit_app
    environment:
      CONFIG_CONTAINER_PATH: ${CONFIG_CONTAINER_PATH}
      BACKEND_HOST: http://inf_backend:8000
      DAGSTER_POSTGRES_USER: ${POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      DAGSTER_POSTGRES_HOST: ${POSTGRES_HOST}
      INF_POSTGRES_DB: ${INF_POSTGRES_DB}

    image: streamlit_app_image
    ports:
      - "8501:8501"  # Expose Streamlit port
    expose:
      - "8501"
    volumes:
      - config_volume:/app/config  # Mount shared config.yaml
      - training_runs:/app/training_runs  # Mount shared training runs volume
    networks:
      - app_network

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      MLFLOW_POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}

    networks:
      - app_network
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"  # Expose PostgreSQL port
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${DAGSTER_POSTGRES_DB}']
      interval: 10s
      timeout: 8s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  init-postgresdb:
    image: postgres:11
    container_name: init_postgresdb
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "bash /init_dbs.sh"
    volumes:
      - ./dbscripts/init_dbs.sh:/init_dbs.sh
      - ./dbscripts/init_sql.sql:/init_sql.sql

    
  mlflow:
    build:
      context: .
      dockerfile: ${DOCKER_FILES_DIRECTORY}/Dockerfile_mlflow
    container_name: mlflow_tracking
    image: mlflow_tracking_image

    environment:
      MLFLOW_TRACKING_URI: http://mlflow:${MLFLOW_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      MLFLOW_POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      MLFLOW_PORT: ${MLFLOW_PORT}
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"  # Expose MLflow port
    networks:
      - app_network
    volumes:
      - mlflow_artifacts:/mlflow/artifacts  # Mount shared MLflow artifacts volume
      - config_volume:/app/config  # Mount shared config.yaml
    depends_on:
      postgres:
        condition: service_healthy
      init-postgresdb:
        condition: service_completed_successfully

  inf_backend:
    build:
      context: .
      dockerfile: ${DOCKER_FILES_DIRECTORY}/Dockerfile_inf_backend
      args:
        DAGSTER_TRADING_FUNCTIONS_PATH: ${DAGSTER_TRADING_FUNCTIONS_PATH}
    container_name: inf_backend
    image: inf_backend_image
    ports:
      - "${INFERENCE_BACKEND_PORT}:${INFERENCE_BACKEND_PORT}"  # Expose inference backend port
    expose:
      - "${INFERENCE_BACKEND_PORT}"
    environment:
      CONFIG_PATH: ${CONFIG_CONTAINER_PATH}
      EXCEL_OHLC_DATA_PATH: ${DATA_CONTAINER_PATH}/SPY_AllData.xlsx
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      INF_POSTGRES_DB: ${INF_POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - app_network
    volumes:
      - mlflow_artifacts:/mlflow/artifacts  # Mount shared MLflow artifacts volume
      - data_volume:${DATA_CONTAINER_PATH}  # Mount shared data volume
      - config_volume:/app/config  # Mount shared config.yaml
      

  inf_frontend:
    build:
      context: .
      dockerfile: ${DOCKER_FILES_DIRECTORY}/Dockerfile_inf_frontend
    container_name: inf_frontend
    image: inf_frontend_image
    ports:
      - "${INFERENCE_FRONTEND_PORT}:${INFERENCE_FRONTEND_PORT}"  # Expose inference frontend port
    expose:
      - "${INFERENCE_FRONTEND_PORT}"
    networks:
      - app_network
    volumes:
      - config_volume:/app/config  # Mount shared config.yaml
    environment:
      NEXT_PUBLIC_INF_URL: http://localhost:${INFERENCE_BACKEND_PORT}
      NEXT_PUBLIC_LOW_MODEL_NAME: xgboost_power_low
      NEXT_PUBLIC_HIGH_MODEL_NAME: xgboost_power_high
      PORT: ${INFERENCE_FRONTEND_PORT}
      NEXT_PUBLIC_MAX_SPEED: 20

  dagster_code:
    build:
      context: .
      dockerfile: ${DOCKER_FILES_DIRECTORY}/Dockerfile_dagster_trading
      args:
        DAGSTER_CODE_LOCATION: ${DAGSTER_CODE_LOCATION}
        DAGSTER_CODE_PORT: ${DAGSTER_CODE_PORT}
        DAGSTER_TRADING_FUNCTIONS_PATH: ${DAGSTER_TRADING_FUNCTIONS_PATH}
    container_name: dagster_code
    image: dagster_code_image    
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: ${POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      DAGSTER_POSTGRES_HOST: ${POSTGRES_HOST}
      DAGSTER_POSTGRES_PORT: ${POSTGRES_PORT}
      DAGSTER_CODE_PORT: ${DAGSTER_CODE_PORT}
      CONFIG_CONTAINER_PATH: ${CONFIG_CONTAINER_PATH}
      DATA_CONTAINER_PATH: ${DATA_CONTAINER_PATH}
      DAGSTER_CODE_LOCATION: ${DAGSTER_CODE_LOCATION}
      DAGSTER_TRADING_FUNCTIONS_PATH: ${DAGSTER_TRADING_FUNCTIONS_PATH}
      INF_POSTGRES_DB: ${INF_POSTGRES_DB}

    networks:
      - app_network
    volumes:
      - config_volume:/app/config  # Mount shared config.yaml
      - data_volume:${DATA_CONTAINER_PATH}  # Mount shared data volume
      - training_runs:/app/training_runs  # Mount shared training runs volume
      - dagster_local_artifacts:/app/dagster_local_artifacts  # Mount dagster local artifacts volume
    

  dagster_webserver:
    build:
      context: .
      dockerfile: ${DOCKER_FILES_DIRECTORY}/Dockerfile_dagster
      args:
        CONFIG_DIRECTORY: ${CONFIG_DIRECTORY}
    entrypoint: ["dagster-webserver", "-h", "0.0.0.0", "-p", "${DAGSTER_WEBSERVER_PORT}", "-w", "workspace.yaml"]
    container_name: dagster_webserver
    ports:
      - "${DAGSTER_WEBSERVER_PORT}:${DAGSTER_WEBSERVER_PORT}"  # Expose Dagster webserver port
    expose:
      - '${DAGSTER_WEBSERVER_PORT}'
    environment:
      DAGSTER_WEBSERVER_PATH_PREFIX: ${DAGSTER_WEBSERVER_PATH_PREFIX}
      DAGSTER_POSTGRES_USER: ${POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      DAGSTER_POSTGRES_HOST: ${POSTGRES_HOST}
      DAGSTER_POSTGRES_PORT: ${POSTGRES_PORT}
      DAGSTER_CODE_PORT: ${DAGSTER_CODE_PORT}
      LOCAL_ARTIFACTS_BASE_DIR: ${DAGSTER_FILES_CONTAINER_DIRECTORY}/artifacts
      COMPUTE_LOGS_BASE_DIR: ${DAGSTER_FILES_CONTAINER_DIRECTORY}/compute_logs
      CONFIG_CONTAINER_PATH: ${CONFIG_CONTAINER_PATH}
      INF_POSTGRES_DB: ${INF_POSTGRES_DB}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - config_volume:/app/config  # Mount shared config.yaml
      - dagster_files:/opt/dagster_files  # Mount dagster files volume
      - data_volume:${DATA_CONTAINER_PATH}  # Mount shared data volume
      - training_runs:/app/training_runs  # Mount shared training runs volume
      - dagster_local_artifacts:/app/dagster_local_artifacts  # Mount dagster local artifacts volume
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy
      dagster_code:
        condition: service_started
      init-postgresdb:
        condition: service_completed_successfully

  dagster_daemon:
    build:
      context: .
      dockerfile: ${DOCKER_FILES_DIRECTORY}/Dockerfile_dagster
      args:
        CONFIG_DIRECTORY: ${CONFIG_DIRECTORY}
    entrypoint: ["dagster-daemon", "run"]
    container_name: dagster_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: ${POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      DAGSTER_POSTGRES_HOST: ${POSTGRES_HOST}
      DAGSTER_POSTGRES_PORT: ${POSTGRES_PORT}
      DAGSTER_CODE_PORT: ${DAGSTER_CODE_PORT}
      LOCAL_ARTIFACTS_BASE_DIR: ${DAGSTER_FILES_CONTAINER_DIRECTORY}/artifacts
      COMPUTE_LOGS_BASE_DIR: ${DAGSTER_FILES_CONTAINER_DIRECTORY}/compute_logs
      CONFIG_CONTAINER_PATH: ${CONFIG_CONTAINER_PATH}
      INF_POSTGRES_DB: ${INF_POSTGRES_DB}
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - config_volume:/app/config  # Mount shared config.yaml
      - data_volume:${DATA_CONTAINER_PATH}  # Mount shared data volume
      - training_runs:/app/training_runs  # Mount shared training runs volume
      - dagster_local_artifacts:/app/dagster_local_artifacts  # Mount dagster local artifacts volume
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy
      dagster_code:
        condition: service_started
      init-postgresdb:
        condition: service_completed_successfully

volumes:

  dagster_files:
    driver: local
    driver_opts:
      type: none
      device: ${WORKING_DIRECTORY}/dagster_files  # Your local folder for dagster files
      o: bind

  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${WORKING_DIRECTORY}/pgdata  # Your local folder for PostgreSQL data
      o: bind

  config_volume:
    driver: local
    driver_opts:
      type: none
      device: ${WORKING_DIRECTORY}/Config  # Your local folder containing config.yaml
      o: bind

  data_volume:
    driver: local
    driver_opts:
      type: none
      device: ${WORKING_DIRECTORY}/data  # Your local folder for data storage
      o: bind

  training_runs:
    driver: local
    driver_opts:
      type: none
      device: ${WORKING_DIRECTORY}/training_runs  # Your local folder for training runs
      o: bind

  mlflow_artifacts:
    driver: local
    driver_opts:
      type: none
      device: ${WORKING_DIRECTORY}/mlflow_artifacts  # Your local folder for MLflow artifacts
      o: bind

  mlflow_local_artifacts:
    driver: local
    driver_opts:
      type: none
      device: ${WORKING_DIRECTORY}/local_artifacts  # Your local folder for MLflow local artifacts
      o: bind

  dagster_local_artifacts:
    driver: local
    driver_opts:
      type: none
      device: ${WORKING_DIRECTORY}/dagster_files/dagster_local_artifacts  # Your local folder for dagster artifacts
      o: bind

  certbot_data:
  certbot_www:

networks:
  app_network:
    driver: bridge
    name: app_network
