# Dockerfile.mlflow
FROM python:3.11-slim


# Copy the requirements file into the image
COPY requirements.mlflow.txt .
# Install all packages from requirements.txt
RUN pip install --no-cache-dir -r requirements.mlflow.txt

RUN apt-get update && apt-get install -y postgresql-client

# Create a directory for artifacts
RUN mkdir -p /mlflow/artifacts

# Set working directory
WORKDIR /mlflow

# Expose the MLflow port
EXPOSE 5001

# Default command
CMD ["bash", "-c", "mlflow server \
  --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${MLFLOW_POSTGRES_DB} \
  --default-artifact-root /mlflow/artifacts \
  --host 0.0.0.0 \
  --port ${MLFLOW_PORT}"]