FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster.yaml and workspace.yaml there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/
ARG CONFIG_DIRECTORY
RUN mkdir -p ${DAGSTER_HOME}

COPY ${CONFIG_DIRECTORY}/dagster.yaml ${CONFIG_DIRECTORY}/workspace.yaml ${DAGSTER_HOME}
RUN echo "CONFIG_DIRECTORY: ${CONFIG_DIRECTORY}"

WORKDIR ${DAGSTER_HOME}