# Dockerfile.mlflow
FROM python:3.10-slim


# Install MLflow and Postgres driver
RUN pip install --no-cache-dir mlflow psycopg2-binary

RUN apt-get update && apt-get install -y postgresql-client

# Create a directory for artifacts
RUN mkdir -p /mlflow/artifacts

# Set working directory
WORKDIR /mlflow

# Expose the MLflow port
EXPOSE 5001

# Default command
CMD ["bash", "-c", "mlflow server \
  --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${MLFLOW_POSTGRES_DB} \
  --default-artifact-root /mlflow/artifacts \
  --host 0.0.0.0 \
  --port ${MLFLOW_PORT}"]