FROM python:3.11-slim

# Copy the requirements file into the image
COPY requirements.dagster.txt .
# Install all packages from requirements.txt
RUN pip install --no-cache-dir -r requirements.dagster.txt

# Set $DAGSTER_HOME and copy dagster.yaml and workspace.yaml there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/
ARG CONFIG_DIRECTORY
RUN mkdir -p ${DAGSTER_HOME}

COPY ${CONFIG_DIRECTORY}/dagster.yaml ${CONFIG_DIRECTORY}/workspace.yaml ${DAGSTER_HOME}
RUN echo "CONFIG_DIRECTORY: ${CONFIG_DIRECTORY}"

WORKDIR ${DAGSTER_HOME}