#Base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy streamlit code and requirements
COPY ./ui .

# Install requirements
RUN pip install --no-cache-dir -r requirements.txt

# Run streamlit app with base URL setting
CMD ["streamlit", "run", "Home.py", "--server.address=0.0.0.0"]
