[metadata]
name = rl_functions
version = 0.1.0
description = A collection of functions for reinforcement learning in trading applications.
author = Rahul Pradeep
license = MIT

[options]
package_dir =
    = src
packages = find:
install_requires =
    pandas
    numpy
    dagster
    scikit-learn
    optuna
    optuna_integration
    mlflow
    PyYAML
    sqlalchemy
    psycopg2-binary
    pydantic
    stable-baselines3
    gymnasium
    torch

[options.packages.find]
where = src