[metadata]
name = rl_functions
version = 0.1.0
description = A collection of functions for reinforcement learning in trading applications.
author = Rahul Pradeep
license = MIT

[options]
package_dir =
    = src
packages = find:
install_requires =
    pandas >=2.3,<2.4
    numpy >=2.2,<2.3
    mlflow >=3.2,<3.3
    PyYAML >=6.0,<6.1
    sqlalchemy >=2.0,<2.1
    psycopg2-binary >=2.9,<3.0
    pydantic >=2.11,<2.12
    stable-baselines3 >=2.7,<2.8
    sb3-contrib >=2.7,<2.8
    gymnasium >=1.2,<1.3

[options.packages.find]
where = src