[metadata]
name = trading_functions
version = 0.1.0
description = A collection of functions for trading strategies and analysis.
author = Rahul Pradeep
license = MIT

[options]
packages = find:
install_requires =
    pandas
    numpy
    dagster
    scikit-learn
    optuna
    xgboost
    mlflow
    openpyxl
    joblib

[options.packages.find]
where = .