ops:
  load_data:
    config:
      all_data_path: ../data/SPY_AllData.xlsx
      end_date: 2023-01-31
      sheet_names: 1minData1-6-2022,1minData1-12-2023
      start_date: 2023-01-01
  add_indicators:
    config:
      bolband_period: 20
      bolband_width: 2
      donchn_period: 20
      tchr_period: 100
      tchr_retracement: long
      tchr_adj: 5
      tchr_range: highlow
      adwm_period: 14
      wasi_limit: 3
      volume_ma_period: 10
      atr_period: 14
      atr_ma: 20