# /etc/nginx/nginx.conf
worker_processes auto;
events {
    worker_connections 1024;
}

# TCP Layer 4 proxy
stream {
    include /etc/nginx/conf.d/*.stream;
}

http {
    include       /etc/nginx/mime.types;
    include       /etc/nginx/conf.d/*.conf;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
}
