common_config:
  close_transform_columns: bolband,donchn,pivot,ma_20,ma_50,ma_100,ema_20
  initial_columns: Date,Open,High,Low,Close,Volume
  label_scaling_multiplier: 10000
  normalize_timegap_threshold: 60
  num_bars_to_look_labels: 20
indicators:
  available: bolband,donchn,tchr,adwm,wasi,volume_ma,atr,fourier,volatility,momentum,pivot,ma_20,ma_50,ma_100,ema_20
  functions:
    atr: calculate_ATR
    bolband: add_bollinger_bands
    donchn: add_donchian_bands
    ema: add_EMA
    fourier: compute_fourier_df
    ma: add_MA
    momentum: add_momentum
    pivot: add_pivot
    tchr: calculate_tchr
    volatility: add_volatility
  indicator_column: Close
  parameters:
    atr:
      columns: ATR,ADJATR
      ma: 20
      period: 14
    bolband:
      columns: BOLLBU,BOLLBL
      period: 20
      width: 2
    donchn:
      columns: DONUP,DONLOW
      period: 20
    fourier:
      period: 50
    momentum:
      columns: Momentum
      window: 10
    pivot:
      columns: PVPT,PVPTR1,PVPTR2,PVPTR3,PVPTS1,PVPTS2,PVPTS3
    tchr:
      adj: 5
      columns: TCHR
      period: 100
      range: highlow
      retracement: long
    volatility:
      columns: Volatility
      window: 14
  selected: bolband,donchn,tchr,atr,fourier,volatility,momentum,pivot,ma_20,ma_50,ma_100,ema_20
mlflow:
  experiment_name: xgboost_power
  tracking_uri: http://mlflow:5001
scaling:
  minmax:
    columns: bolband,donchn,tchr,atr,volatility,momentum,pivot,ma_20,ma_50,ma_100,ema_20
  robust:
    columns: ''
  standard:
    columns: ''
trade_parameters:
  amount_per_trade: 10
  trade_init_ratio_threshold: 3
  trade_risk_ratio_threshold: 0.8
training_details:
  all_data_path: /app/data/SPY_AllData.xlsx
  early_stopping_rounds: 300
  eval_metric: quantile
  high_label_column: High_Label
  low_label_column: Low_Label
  mlflow_config_artifact_name: training_config.yaml
  model_name: xgboost_power
  num_boost_rounds: 20000
  num_trials: 50
  parquet_viewer_link: http://localhost:8501/parquet_viewer
  qalpha_high: 0.25,0.9
  qalpha_low: 0.25,0.9
  random_state: 42
  runs_folder: /app/training_runs
  sheet_names: 1minData1-6-2022,1minData1-12-2023
  test_end_date: '2023-02-11'
  test_size: 0.2
  test_start_date: '2023-02-01'
  train_end_date: '2023-01-13'
  train_start_date: '2023-01-01'
training_parameters:
  active_parameters: objective,tree_method,eval_metric,gamma,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,lambda,alpha
  base_parameters: objective,tree_method,eval_metric
  params_list:
  - hp: false
    log: false
    name: objective
    type: str
    value: reg:quantileerror
  - hp: false
    log: false
    name: tree_method
    type: str
    value: hist
  - hp: false
    log: false
    name: eval_metric
    type: str
    value: quantile
  - hp: true
    log: false
    max: 10.0
    min: 0.0
    name: gamma
    type: float
    value: 3.2
  - hp: true
    log: false
    max: 12
    min: 3
    name: max_depth
    type: int
    value: 6
  - hp: true
    log: true
    max: 0.3
    min: 0.001
    name: learning_rate
    type: float
  - hp: true
    log: false
    max: 1.0
    min: 0.5
    name: subsample
    type: float
  - hp: true
    log: false
    max: 1.0
    min: 0.5
    name: colsample_bytree
    type: float
  - hp: true
    log: false
    max: 10.0
    min: 1.0
    name: min_child_weight
    type: float
  - hp: true
    log: false
    max: 10.0
    min: 0.0
    name: lambda
    type: float
  - hp: true
    log: false
    max: 10.0
    min: 0.0
    name: alpha
    type: float
